### ISSUE TITLE
Rendering slowness

### ISSUE THREAD

**Issue by Kabouik** [rougier/nano-mu4e#3]
> The current mu4e thread folding is the fastest I managed to code because it does not require processing mails before folding (It's done just in time) and this is the reason it has been merged. The mu4e-thread-folding is a bit slower (but offer more options). One of the difficulty is to know if a line is the root of a thread or a child while not all mails have been processed yet. I somehow solved this with nano-mu4e and the only important part is the [nano-mu4e--instrument](https://github.com/rougier/nano-mu4e/blob/master/nano-mu4e.el#L521) function that instruments all mails just before displaying them. Do you know how many mails do you have ? On my machine, 500 mails is less than a second to index.

 _Originally posted by @rougier in [#33](https://github.com/rougier/mu4e-thread-folding/issues/33#issuecomment-3162579588)_, in response to a comment about slow rendering of the headers view in `nano-mu4e`, _e.g.+_, when pressing `SPC` to cycle views.

I'm replying here so as to avoid polluting the `mu4e-thread-folding` issue tracker (sorry, it was I who started talking about `nano-mu4e` there). Based on your comment, it seems `nano-mu4e` would be a better fit for my use since I will not need advanced threading features, and would favour speed.

My maildir folder contains messages for two accounts for a total of 220k messages in store:

```gnuplot
                              Messages per year matching                       
     35000 +---------------------------------------------------------------+   
           |  +  +   +  +   +  +  +   +  +   +  +   +  +  +   +  +   +  +  |   
     30000 |-+                                    ****                   +-|   
           |                                      *##*                     |   
           |                                      *##*                     |   
     25000 |-+                                    *##*                   +-|   
           |                                      *##*   ****   *******    |   
     20000 |-+                                    *##*   *##*****##*##*  +-|   
           |                                      *##*   *##*##**##*##*    |   
           |                                      *##*****##*##**##*##**** |   
     15000 |-+                                 ****##*##**##*##**##*##*##*-|   
           |                                   *##*##*##**##*##**##*##*##* |   
     10000 |-+                      ****       *##*##*##**##*##**##*##*##*-|   
           |              ***********##*********##*##*##**##*##**##*##*##* |   
           |              *##**##*##*##**##*##**##*##*##**##*##**##*##*##* |   
      5000 |-+            *##**##*##*##**##*##**##*##*##**##*##**##*##*##*-|   
           |  +  +   +  + *##**##*##*##**##*##**##*##*##**##*##**##*##*##* |   
         0 +---------------------------------------------------------------+   
            19720092012011201201201420120162012018201202202120220232022025     
                                         Year 
```

I don't know if this matters, but one of the two accounts has most its emails (107k) in `~/.mail/account/inbox` (not using folders on that one), while the other one has `inbox/subfolders` per year and `mu4e`'s inbox for that account is set to only show the current year subfolder.

I show 1000 results instead of the default 500 with `(setq mu4e-headers-results-limit 1000)`.

The slowness I experienced was only with `nano-mu4e`: toggling threading on and off with `P` `t` in base `mu4e` was relatively fast. But this was also a very preliminary test of `nano-mu4e` and maybe there are some conflicts with my pre-existing `mu4e` configuration that I just have not detected yet.

**Comment by Kabouik** [comment]
Could you confirm whether `nano-mu4e` is responsible for opening many files as buffers (*e.g.*, to compute the threads)? If not, there's a bug in my configuration, but this only happens with `nano-mu4e-mode` enabled so it's worth asking.

<img width="1940" height="410" alt="Image" src="https://github.com/user-attachments/assets/e137bf12-3dbc-4bef-a612-47468eae1d53" />

It's probably the cause of the slow rendering in my case.

**Comment by rougier** [comment]
Oh, I fixed this annoying opening (and forgot to push). In fact, There's a preview option for new mail that is activated by default and this might be the ideal suspect. Give me a second to fix it.

**Comment by rougier** [comment]
Done! Can you test the new version ?

**Comment by Kabouik** [comment]
Heh, glad my issue at least allowed realizing that that commit was not pushed. Unfortunately the issue still is there, many files are opened as buffers. 

This only happens when `nano-mu4e-mode` is enabled, but my `mu4e` configuration is still a mess because I've only recently started using it and put together many Elisp blocks that I found here and there. I need to sort it to see if something might be conflicting somehow; I'd really like to use `nano-mu4e`.

**Comment by Kabouik** [comment]
My bad. I cloned master and loaded the package again, but I did not restart my Emacs daemon. I overlooked that the option was perhaps still enabled. Restarting the daemon now fixed it: no more hundreds of files opened as buffers, and overall a much better experience! Exciting. The optional preview feature looks interesting though.

I still need to configure everything because some icons (provided by `svg-lib` I guess) are correctly shown but some are not:

<img width="588" height="681" alt="Image" src="https://github.com/user-attachments/assets/c7f4984c-4983-49ad-8ea5-35eac65ea6e5" />

And the headers get garbled every time I quit `message-view`:

<img width="1905" height="103" alt="Image" src="https://github.com/user-attachments/assets/e21cba6d-4ca4-4223-8167-b51cf16e4028" />

The latter is probably related to my custom `mu4e-headers-fields` configuration, but I wish it would be possible to reconcile them with `nano-mu4e`:

```emacs-lisp
(setq mu4e-headers-date-format "%Y-%m-%d %H:%M")
(add-hook 'mu4e-headers-mode-hook
      (defun my/mu4e-change-headers ()
	(interactive)
	(setq mu4e-headers-fields
              `((:human-date . 18) ;; alternatively, use :date
		(:flags . 6)
		(:mailing-list . 15)
		(:from . 22)
		(:subject . ,(- (window-body-width) 75)) ;; alternatively, use :thread-subject
		(:size . 7)))))
```

I imagine I would need to set them only when `nano-mu4e-mode` is disabled, and restore the default whenever `nano-mu4e-mode` is enabled, but I don't know how to do that yet.

Anyhow, I think the slowness issue is resolved. Thank you.

**Comment by rougier** [comment]
You can replace the icons with the `nano-mu4e-symbols` variable. I'm using NERD fonts (https://www.nerdfonts.com/) to have a nice set of symbols with pretty much any font.

As for the mu4e-headers-fields, you can try something like:

```emacs-lisp
(add-hook 'nano-mu4e-mode-hook
    (lambda ()
        (setq mu4e-headers-fields '((:nano-mu4e)))))
```

**Comment by Kabouik** [comment]
Thanks. I had some `emacs-nerd-*` packages installed from Guix, but I missed that nerd fonts are actually font-specific. Things seem to be rendering much better now that I specifically downloaded the Iosevka nerd fonts and updated the font cache. All good. Sometimes I can see that some icons fail to load properly and the garbled icon is shown instead, but the icon is present on the system because marking the message with a flag and then removing it usually fixes it.

The hook did not solve the issue, however, but I confirmed the snippet I posted above is the one responsible for the issue. I'll try to investigate how can I can combine both configurations so that I can use `nano-mu4e` but don't have to.
